version: '3.8'

services:
  nozomi-mysql:
    build:
      context: ./infra/mysql
      args:
        MYSQL_ROOT_PASSWORD: "password"
    image: nozomi-db:latest
    volumes:
      - ./infra/mysql/db:/var/lib/mysql
      - ./infra/mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4
    ports:
      - 3306:3306