version: '3.8'

services:
  nozomi-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      LANG: C.UTF-8
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
  dev-ruby:
    build:
      context: ./infra/ruby
    image: nozomi-dev-ruby:latest
    environment:
      MYSQL_HOST: nozomi-mysql
    volumes:
      - ./:/working