common: &common
  adapter: 'mysql2'
  encoding: utf8mb4
  collation: utf8mb4_bin

local: &local
  host: '127.0.0.1'
  port: 3306
  username: root
  password: password

development:
  <<: *common
  <<: *local
  database: nozomi_development

test:
  <<: *common
  <<: *local
  database: nozomi_test
