# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Backend unit tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        ports: ['3306:3306']
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          LANG: C.UTF-8
          TZ: Asia/Tokyo
      dind:
        image: docker:dind
        ports: ['2376:2376']
        volumes:
          - docker_cert:/certs/client
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run bundle install
        run: |
          gem install bundler
          bundle install
      - name: Migrate the database
        env:
          ENV: test
          DOCKER_CLIENT_CERTPATH: docker_cert
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
      - name: Run test task
        run: ./gradlew test
        env:
          DOCKER_CLIENT_HOST: unix:///var/run/docker.sock
